// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        //return ios;
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /*
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsFL2ZF4ZMOch45khhsalf6ADEFsnK6PA',
    appId: '1:733690520391:android:ea841fc985f27ed336a262',
    messagingSenderId: '733690520391',
    projectId: 'fluttercoffeeeffectivelab',
    storageBucket: 'fluttercoffeeeffectivelab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYRpHY4GC9ZOPfdwTtz5TQzHf5fTROyic',
    appId: '1:733690520391:ios:5d7e715de599579836a262',
    messagingSenderId: '733690520391',
    projectId: 'fluttercoffeeeffectivelab',
    storageBucket: 'fluttercoffeeeffectivelab.appspot.com',
    iosBundleId: 'com.example.flutterCourse',
  );*/

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD05NQTa24OElt7xbSyzK3AsF1qCXgH5eg',
    appId: '1:682223097542:android:6608623c36e3caf0dda9c7',
    messagingSenderId: '682223097542',
    projectId: 'cooffeeshop-flutter-academy',
    storageBucket: 'cooffeeshop-flutter-academy.appspot.com',
  );
}
